on:
  push:
    branches:
      - 'main'
    paths:
      - 'DESCRIPTION'
  workflow_dispatch:

jobs:
  drat-upload:
    runs-on: ubuntu-20.04
    name: Drat Upload
    steps:
      - uses: mikemahoney218/upload-to-drat-repo@v0.3
        with:
          drat_repo: 'INWTlab/drat'
          token: "${{ secrets.GH_ACTION_DRAT }}"
          commit_message: "deploy to drat - update dbtools via gh actions"
          commit_email: "brother-mfc@inwt-statistics.de"
          archive: true
